# AppVeyor.yml from https://github.com/ogrisel/python-appveyor-demo
# License: CC0 1.0 Universal: http://creativecommons.org/publicdomain/zero/1.0/

build: off

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

init:
  - git config --global core.autocrlf input
  - git config --global core.longpaths true

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
 files:
   - docs/*
   - '**/*.html'
   - '**/*.rst'
   - HISTORY.txt

environment:

  # Create expected SHELL variable for pipenv.
  SHELL: "windows"
  PYPI_VENDOR_DIR: "%cd%\\tests\\pypi\\"

  matrix:

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

install:
  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & _appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET PYTHONIOENCODING=utf-8"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "pip install -e . --upgrade"
  - "pipenv install --system --dev --skip-lock"

test_script:
  - "pipenv run pytest -n 8 -m cli"
  - "pipenv run pytest -n 8 -m dotvenv"
  - "pipenv run pytest -n 8 -m check"
  - "pipenv run pytest -n 8 -m unused"
  - "pipenv run pytest -n 8 -m requirements"
  - "pipenv run pytest -n 8 -m complex"
  - "pipenv run pytest -n 8 -m run"
  - "pipenv run pytest -n 8 -m project"
  - "pipenv run pytest -n 8 -m utils"
  - "pipenv run pytest -n 8 -m takes-forever"
